export enum ROLES {
  ADMIN = "ADMIN",
  HEAD_DEPARTMENT = "CHU_NHIEM_BO_MON",
  PLANNER = "NGUOI_LAP_KE_HOACH",
  TEACHER = "GIANG_VIEN",
  STUDENT = "SINH_VIEN",
  HEAD_SUBJECT = "TRUONG_MON",
  SUPER_ADMIN = "SUPER_ADMIN",
}
