name: Build and Deploy Tutor Management To Docker Hub

on:
  push:
    tags:
      - "*"
    branches:
      - stage

jobs:
  build-deploy:
    name: build and push tutor-api and tutor-client to docker hub
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: unit tests
        working-directory: ./server
        run: ./gradlew test

      - name: build the app
        working-directory: ./server
        run: ./gradlew build

      - name: setup Node.js 20 for tutor-client
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: install js dependencies with yarn
        working-directory: ./client
        run: yarn install

      - name: build the tutor-client app with npm
        working-directory: ./client
        run: yarn run build:stage

      - name: get GitHub tag
        id: vars
        run: echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: build the docker image for tutor-api
        uses: docker/build-push-action@v4
        with:
          context: ./server
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-api:${{ env.GITHUB_TAG }}

      - name: build the docker image for tutor-client
        uses: docker/build-push-action@v4
        with:
          context: ./client
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-client:${{ env.GITHUB_TAG }}

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image for tutor-api to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./server
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-api:${{ env.GITHUB_TAG }}

      - name: push the docker image for tutor-client to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./client
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tutor-client:${{ env.GITHUB_TAG }}
